export const PORTFOLIO_CONTENT = [
  {
    article_id: 'about',
    title: 'About Ankit',
    section_id: 'about',
    section_anchor: '#about',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'about',
    article_slug_es: 'about',
    keywords: ['ankit', 'about', 'background', 'bio', 'story', 'who is ankit', 'introduction'],
    content: `Ankit Das is an AI/software and full-stack engineer based in Sewanee, Tennessee. He is pursuing dual B.S. degrees in Mathematics and Computer Science at The University of the South with a 3.93 GPA and plans to graduate in May 2026. His work sits at the intersection of AI systems, geospatial technology, backend infrastructure, and product-minded application development. He likes building systems that translate complex data into tools people can actually use.`,
  },
  {
    article_id: 'education',
    title: 'Education',
    section_id: 'education',
    section_anchor: '#education',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'education',
    article_slug_es: 'education',
    keywords: ['education', 'school', 'university', 'sewanee', 'gpa', 'coursework', 'graduation', 'beecken scholar', 'study abroad', 'booth'],
    content: `Ankit studies Mathematics and Computer Science at The University of the South in Sewanee, Tennessee. He has a 3.93 GPA and is graduating in May 2026. Honors and leadership roles include Honors Scholar on a full ride, Beecken Business Scholar, Dean's List every semester, Math Club President, Sewanee Computing Society Vice President, and Resident Assistant. He also spent a semester abroad at Universidad Carlos III de Madrid in spring 2025 studying computer science and business, and completed The University of Chicago Booth School of Business Summer Business Scholars Program: Building the New Venture through the Beecken Scholar opportunity. Relevant coursework includes data structures and algorithms, databases, computer systems, software development, probability and statistics, computer graphics, multivariable calculus, network theory, and theory of computation.`,
  },
  {
    article_id: 'education-programs',
    title: 'Additional Education and Programs',
    section_id: 'education',
    section_anchor: '#education',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'education-programs',
    article_slug_es: 'education-programs',
    keywords: ['universidad carlos iii de madrid', 'madrid', 'semester abroad', 'computer science and business', 'uchicago booth', 'booth school of business', 'summer business scholars', 'building the new venture', 'entrepreneurship'],
    content: `Ankit studied abroad at Universidad Carlos III de Madrid from January 2025 through May 2025 in computer science and business, gaining an international perspective on technology and management. In 2024, he also completed The University of Chicago Booth School of Business Summer Business Scholars Program: Building the New Venture as part of the Beecken Scholar opportunity. That program focused on entrepreneurial foundations such as market analysis, product prototyping, marketing strategy, and press-release style startup communication through hands-on work.`,
  },
  {
    article_id: 'experience-trc',
    title: 'TRC Companies',
    section_id: 'trc',
    section_anchor: '#experience',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'experience-trc',
    article_slug_es: 'experience-trc',
    keywords: ['trc', 'trc companies', 'geospatial', 'utility network', 'esri', 'sap', 'postgis', 'pgvector', 'aws lambda', 'rag', 'intent routing'],
    content: `At TRC Companies, Ankit works as an AI and Software Engineer in a part-time and intern capacity. He designed and deployed a production RAG pipeline using pgvector and AWS Lambda to answer geospatial utility questions in seconds. He built dual-domain intent routing with guardrails that filter malicious prompts and help protect SAP-related business data. He shipped React and Python full-stack features with JWT authentication and advanced caching that reduced API costs by 60 percent and improved performance by 85 percent. He also integrated ESRI Utility Network tracing with PostGIS so field engineers could identify fault locations in under a minute.`,
  },
  {
    article_id: 'experience-spectrum',
    title: 'Spectrum / Charter',
    section_id: 'spectrum',
    section_anchor: '#experience',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'experience-spectrum',
    article_slug_es: 'experience-spectrum',
    keywords: ['spectrum', 'charter', 'spring boot', 'java 17', 'graphql', 'rest', 'log4j', 'veracode', 'cassandra', 'redis', 'postgresql'],
    content: `At Spectrum and Charter Communications, Ankit worked as a Software Engineering Intern in Denver during summer 2024. He migrated six enterprise REST and GraphQL services to Java 17 and Spring Boot 3, eliminating more than ten critical Log4j vulnerabilities and improving response times by 15 percent. He optimized testing and Git workflows for the SpectrumEnterprise.net platform and helped automate QA and UAT deployment flows. He also patched Veracode findings and tuned PostgreSQL, Cassandra, and Redis, cutting query latency by 50 percent.`,
  },
  {
    article_id: 'experience-digital-nepal',
    title: 'Digital Nepal',
    section_id: 'digital-nepal',
    section_anchor: '#experience',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'experience-digital-nepal',
    article_slug_es: 'experience-digital-nepal',
    keywords: ['digital nepal', 'notification service', 'spring boot', 'java', 'testing', 'coverage', 'remote'],
    content: `At Digital Nepal, Ankit worked as a Software Engineering Intern and built a Java and Spring Boot notification microservice that automated reminders and reduced manual effort by 30 percent. He introduced a unit testing suite with 85 percent code coverage, which improved stability and reduced post-deployment bugs by 40 percent.`,
  },
  {
    article_id: 'project-dynatrust-rag',
    title: 'DynaTrust-RAG',
    section_id: 'dynatrust-rag',
    section_anchor: '#projects',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'project-dynatrust-rag',
    article_slug_es: 'project-dynatrust-rag',
    keywords: ['dynatrust', 'dynatrust-rag', 'spatiotemporal rag', 'provenance', 'staleness', 'vector search', 'sql retrieval', 'hallucinations'],
    content: `DynaTrust-RAG is a spatiotemporal retrieval system Ankit designed with PostgreSQL, PostGIS, pgvector, and Python. It combines vector retrieval with SQL-style filtering, provenance tracking, and staleness-aware routing. The goal is fast, trustworthy retrieval for domains where time and location matter, with sub-500 millisecond latency and explicit source attribution to reduce hallucinations.`,
  },
  {
    article_id: 'project-tiger-bites',
    title: 'Tiger Bites',
    section_id: 'tiger-bites',
    section_anchor: '#projects',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'project-tiger-bites',
    article_slug_es: 'project-tiger-bites',
    keywords: ['tiger bites', 'food redistribution', 'supabase', 'google maps', 'students', 'food waste'],
    content: `Tiger Bites is a campus food redistribution app Ankit built with React, TypeScript, Supabase, and the Google Maps API. The product enables real-time posts and secure authentication so students can quickly find available food. It was adopted by more than 500 students, reduced food waste by roughly 40 percent, and helped secure 8,000 dollars in fellowship funding.`,
  },
  {
    article_id: 'project-shuttle',
    title: 'Campus Shuttle Tracking System',
    section_id: 'campus-shuttle',
    section_anchor: '#projects',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'project-shuttle',
    article_slug_es: 'project-shuttle',
    keywords: ['shuttle', 'tracking', 'gps', 'websockets', 'react native', 'transportation', 'real-time'],
    content: `The Campus Shuttle Tracking System is a real-time tracker Ankit built with React Native, PostgreSQL, and WebSockets. It sends GPS updates every ten seconds, reduced average wait times by 60 percent, scaled to more than 200 users, and was architected to run at around 80 percent lower cost than vendor alternatives.`,
  },
  {
    article_id: 'project-ats-resume-checker',
    title: 'ATS Resume Checker',
    section_id: 'ats-resume-checker',
    section_anchor: '#projects',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'project-ats-resume-checker',
    article_slug_es: 'project-ats-resume-checker',
    keywords: ['ats resume checker', 'resume analyzer', 'next.js', 'gemini', 'match score', 'caching'],
    content: `ATS Resume Checker is an AI resume analyzer Ankit built with Next.js 15, TypeScript, and Gemini 3 Pro. It extracts ATS keywords, computes match scores, and returns resume feedback quickly. Through aggressive caching, the app cut API costs by 90 percent while keeping 99.5 percent uptime and sub-100 millisecond responses.`,
  },
  {
    article_id: 'project-ai-writing-assistant',
    title: 'AI Writing Assistant',
    section_id: 'ai-writing-assistant',
    section_anchor: '#projects',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'project-ai-writing-assistant',
    article_slug_es: 'project-ai-writing-assistant',
    keywords: ['ai writing assistant', 'drafting assistant', 'thymeleaf', 'jwt', 'java', 'spring boot'],
    content: `AI Writing Assistant is a server-rendered drafting tool Ankit built with Java, Spring Boot, Thymeleaf, and GPT-4. He focused on secure JWT-based authentication and rendering performance, which reduced initial client-side load times by 70 percent.`,
  },
  {
    article_id: 'project-retail-sales-prediction',
    title: 'Retail Sales Prediction',
    section_id: 'retail-sales-prediction',
    section_anchor: '#projects',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'project-retail-sales-prediction',
    article_slug_es: 'project-retail-sales-prediction',
    keywords: ['retail sales prediction', 'forecasting', 'arima', 'ets', 'keras', 'tensorflow', 'r'],
    content: `Retail Sales Prediction is a time-series forecasting project where Ankit compared neural networks against ARIMA and ETS baselines using feature engineering and walk-forward validation. The tuned model improved forecast accuracy by 22 percent.`,
  },
  {
    article_id: 'skills',
    title: 'Skills and Stack',
    section_id: 'skills',
    section_anchor: '#skills',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'skills',
    article_slug_es: 'skills',
    keywords: ['skills', 'stack', 'tech stack', 'languages', 'frameworks', 'cloud', 'tools'],
    content: `Ankit's core languages and frameworks include Python, Java, JavaScript, TypeScript, SQL, C and C++, React, Node.js, and Spring Boot. He works with PostgreSQL, DynamoDB, Redis, AWS services such as Lambda, API Gateway, S3, and RDS, along with Docker and Kubernetes. He also uses GitHub Actions, Jenkins, Kafka, WebSockets, JWT, RabbitMQ, pgvector, PostGIS, REST and GraphQL APIs, JUnit, Postman, and modern AI tooling such as OpenAI API, Gemini, n8n, RAG workflows, and prompt engineering.`,
  },
  {
    article_id: 'contact',
    title: 'Contact',
    section_id: 'contact',
    section_anchor: '#contact',
    page_path_en: '/',
    page_path_es: '/',
    article_slug_en: 'contact',
    article_slug_es: 'contact',
    keywords: ['contact', 'email', 'linkedin', 'github', 'website', 'reach out', 'hire'],
    content: `Ankit can be reached at ankit.das@sewanee.edu. His GitHub is github.com/ankii08 and his LinkedIn is linkedin.com/in/ankitda. He is looking for AI engineering, software engineering, and full-stack roles where he can work on intelligent systems, backend-heavy products, or data-rich user-facing applications.`,
  },
]
